### ISSUE TITLE
Database name could be set on config

### ISSUE THREAD

**Issue by guilhermearaujo** [mneudert/instream#26]
We set many settings on the config, such as host, port, writer, etc.
I believe that a default database name could also be set, and it would be used in every query, unless another database name is provided.

**Comment by mneudert** [comment]
Yep, that one will be a thing "soon"!

Might need some cleanup but I don't see a reason to not include that. Or rather I don't know why this isn't possible already in the first place.

**Comment by mneudert** [comment]
Should be done by now including a proper [test about the priority](https://github.com/mneudert/instream/blob/bb02630e9005f00fd3c8d4d65254e1246981c699/test/instream/connection/database_test.exs). I will probably add some notes to the README about what happens when but it should already work fine :+1: (and hopefully intuitive...)
