### ISSUE TITLE
Another hackney issue?

### ISSUE THREAD

**Issue by daniel1943** [mneudert/instream#35]
`[error] GenServer #PID<0.471.0> terminating
** (FunctionClauseError) no function clause matching in :hackney_headers_new.do_fold/3
    (hackney) /home/home/dev2/phoenix/installer/proj/deps/hackney/src/hackney_headers_new.erl:147: :hackney_headers_new.do_fold([[{3, "Content-Type", 116}], [{4, "Content-Type", 101}], [{5, "Content-Type", 120}], [{6, "Content-Type", 116}], [{7, "Content-Type", 47}], [{8, "Content-Type", 112}], [{9, "Content-Type", 108}], [{10, "Content-Type", 97}], [{11, "Content-Type", 105}], [{12, "Content-Type", 110}]], #Function<6.29524015/3 in :hackney_headers_new.to_iolist/1>, [["Content-Length", ': ', "54", '\r\n'], ["User-Agent", ': ', "hackney/1.7.1", '\r\n'], ["Host", ': ', "localhost:8086", '\r\n']])`

Bug or am I missing something?

**Comment by mneudert** [comment]
I won't go as far as blaming hackney for having an issue, but apparently anything from `1.7.0` onwards raises theses error even when just running the tests locally. And I just hoped having bumped InfluxDB to a non-rc-1.2.x version would make me release a new library version this week :D

A well, perhaps this is just some type conversion foo that is easily solveable...

**Comment by mneudert** [comment]
Yep, you found a bug! :blue_heart: :heart: :green_heart: :purple_heart: :yellow_heart: 

It looks like hackney is treating a list of headers somewhat different since `1.7.0`. Currently the headers are constructed as a list of tuples with having both key and value as char lists. And that was fine until now. But then something changed and it broke.

Changing at least one key or value in at least one header to have a string fixed the problem. A quick check against various hackney versions showed no problem with just setting everything to strings.

I will keep this open until I merge the fix from the branch [`hackney-headers`](https://github.com/mneudert/instream/tree/hackney-headers) to master. Just need to wait a bit as Travis fails to download some InfluxDB versions from GitHub at the moment and I don't have the environment to check those myself...
