### ISSUE TITLE
write queries fail silently

### ISSUE THREAD

**Issue by msambarino** [mneudert/instream#36]
First of all, thanks a lot for this library 👍

I kept trying to write some series today and while this is what I saw on iex:
```ex
[debug] [write] 5 points
:ok
```
The series was not written and `influxdb` logs showed it was returning `400`. 

I eventually found the error on my part, but thought maybe it would be better if `Connection.write` would return an error tuple or something if the write wasn't successful. What do you think? I could make some time to work on this in the coming weeks if you'd be willing to accept a PR.

**Comment by mneudert** [comment]
Could you create a somewhat reproducible case for this?

Until now I sort of ran with the assumption that one should not receive any error (http status >= 400) without a body containing a message. Therefore assuming an empty response is somewhat `:ok` (parsing done [here](https://github.com/mneudert/instream/blob/dd47d9e06a65e79690487410654b55a4a6bf94d1/lib/instream/response.ex#L16)). The method `h.httpError` in the InfluxDB source ([services/http/handler.go](https://github.com/influxdata/influxdb/blob/255992f5ecd76b83827d4caf8d2561846d153cc3/services/httpd/handler.go#880)) seems to also require (and receive) a message to be returned to the client.

Nothing of that means the current implementation is correct. There could always be that one case returning an empty string as an error because it just does it...

**Comment by msambarino** [comment]
I can't!! While trying to create a reproducible case I realized this was my fault, i was swallowing the error. 

Sorry that I wasted your time! I'll close the issue now, thanks for your quick reply!

**Comment by mneudert** [comment]
Ah well, it happens :D

Please don't hesitate to open another issue if you think you have found something :+1:
